### ISSUE TITLE
The app does not work. the code stage failed. note I deployed in Dallas!

### ISSUE THREAD

**Issue by Meaad96s** [IBM/cities-from-space#50]
The app does not work. the code stage failed. note I deployed in Dallas!

**Comment by stevemart** [comment]
Hi @meaad96s sorry you are having issues.

Can you paste and logs you may have from the various stages of the deployment? 

Have you tried to run the app locally?

**Comment by scottdangelo** [comment]
Deploying locally worked for me.
However, when I attempted the `Deploy to IBM Cloud` button it failed to deploy, first with this:

<img width="209" alt="screen shot 2019-02-18 at 8 44 01 am" src="https://user-images.githubusercontent.com/14651388/52962021-759f7080-3359-11e9-8769-b0d3c2a123e5.png">

Then, when I clicked on that tile to `Reconfigure`, I got this:

<img width="1521" alt="screen shot 2019-02-18 at 8 44 12 am" src="https://user-images.githubusercontent.com/14651388/52962055-894ad700-3359-11e9-9b25-32df8119e125.png">

The last time the `Deploy to IBM Cloud` button was tested was 12/18/2018
I'll continue to investigate. In the mean time, I'd suggest you deploy locally, if that is an option.

**Comment by Meaad96s** [comment]
Once I deploy it locally in windows it works but in MacOS it does not! I tried on many devices since I promise to deliver a workshop with this pattern. anyhow, I wish deploying to cloud is option because locally it took more than 30min which is a lot since we have a workshop time frame.

**Comment by Meaad96s** [comment]
Once I deploy it locally in windows it works but in MacOS it does not! I tried it on many devices since I promise to deliver a workshop with this pattern. anyhow, I wish deploying to cloud is an option because locally it took more than 30min which is a lot since we have a workshop time frame.

**Comment by scottdangelo** [comment]
Interesting. I used my mac and it works fine.
What kind of error do you get on the Mac?
Also, keep in mind that it takes a few minutes (around 5) to train the classifiers. It should not take 30 minutes.

**Comment by Meaad96s** [comment]
<img width="1280" alt="screen shot 2019-02-18 at 10 32 12 pm" src="https://user-images.githubusercontent.com/20974667/52972909-60642980-33cd-11e9-8938-5e2ddc3cb05d.png">

**Comment by scottdangelo** [comment]
I'd follow the tip in the Error and:
Please try running this command again as root/Administrator

**Comment by scottdangelo** [comment]
I was able to deploy the app to the cloud using the `Deploy to IBM Cloud` button. Can you please try this again?

**Comment by Meaad96s** [comment]
@scottdangelo The problem is the icon (View my app) does not show! so the app is never deployed.

**Comment by Meaad96s** [comment]
Also I face other problems once I tried to deploy it in my personal account the API Key attributes are generated when I press create. I tried to change the domain back to bluemix but same problem.
![screenshot 109](https://user-images.githubusercontent.com/20974667/52999754-a9e95e80-3437-11e9-9390-6d4ff57b156c.png)

**Comment by scottdangelo** [comment]
Yes, I have had issues with the GUI for IBM cloud failing to refresh. You can try to delete all IBM cookies.
I am going to close this issue, since your current problems are not with this code. You could take up any IBM cloud GUI issues with the support team.
